/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CharityTracker;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brian2
 */
public class CharityTrackerForm extends javax.swing.JFrame {

    private class mytablemodel extends DefaultTableModel {

        mytablemodel(Object[] columnNames, int rowCount) {
            super(columnNames, rowCount);
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
    private final String cPattern = ",";
    private final String pPattern = "!";
    private final String modPattern = "%";
    private final String ampPattern = "&";
    private DefaultListModel donorModel = new DefaultListModel();
    private DefaultListModel charityModel = new DefaultListModel();
    private mytablemodel tableModel = new mytablemodel(new Object[]{"Donor", "Amount", "Charity", "Date"}, 0);
    private ArrayList<Donor> donorList = new ArrayList<Donor>();
    private ArrayList<Charity> charityList = new ArrayList<Charity>();
    private DBEngine db = new DBEngine();

    private void ClearDialogs() {
        txtNewCharityName.setText("");
        txtNewCharityTaxId.setText("");
        txtNewDonorName.setText("");
        txtNewDonorPhone.setText("");
    }

    private void ClearModels() {
        donorModel.clear();
        charityModel.clear();
        donorList.clear();
        charityList.clear();
        tableModel.setRowCount(0);
    }

    private void RebuildTable() {
        String donorname, donationamount, charityname, donationdate;
        for (Donor D : donorList) {
            for (Donation DD : D.getHistory()) {
                donorname = D.getName();
                donationamount = "$" + Double.toString(DD.getAmount());
                charityname = DD.getCharity().getName();
                donationdate = DD.getDate();
                tableModel.addRow(new Object[]{donorname, donationamount, charityname, donationdate});
            }
        }
    }

    /**
     * Creates new form CharityTrackerForm
     */
    public CharityTrackerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgNewDonor = new javax.swing.JDialog();
        lblNewDonorName = new javax.swing.JLabel();
        txtNewDonorName = new javax.swing.JTextField();
        lblNewDonorPhone = new javax.swing.JLabel();
        txtNewDonorPhone = new javax.swing.JTextField();
        btnCreateNewDonor = new javax.swing.JButton();
        btnNewDonorCancel = new javax.swing.JButton();
        dlgNewCharity = new javax.swing.JDialog();
        lblNewCharityName = new javax.swing.JLabel();
        txtNewCharityName = new javax.swing.JTextField();
        lblNewCharityTaxId = new javax.swing.JLabel();
        txtNewCharityTaxId = new javax.swing.JTextField();
        btnCreateNewCharity = new javax.swing.JButton();
        btnNewDonorCancel1 = new javax.swing.JButton();
        dlgDonationsTable = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDonationsTable = new javax.swing.JTable();
        btnCloseDonationTable = new javax.swing.JButton();
        pnlDonorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDonorBox = new javax.swing.JList();
        btnNewDonor = new javax.swing.JButton();
        pnlCharityPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCharityBox = new javax.swing.JList();
        btnNewCharity = new javax.swing.JButton();
        pnlDonationPanel = new javax.swing.JPanel();
        txtDonationAmountBox = new javax.swing.JTextField();
        btnMakeDonation = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mitemOpen = new javax.swing.JMenuItem();
        mitemSave = new javax.swing.JMenuItem();
        mitemExit = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        mitemDisplayDonations = new javax.swing.JMenuItem();

        dlgNewDonor.setTitle("New Donor");
        dlgNewDonor.setBounds(new java.awt.Rectangle(4, 22, 301, 204));

        lblNewDonorName.setText("Name");

        lblNewDonorPhone.setText("Phone Number");

        btnCreateNewDonor.setText("Ok");
        btnCreateNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewDonorCmd(evt);
            }
        });

        btnNewDonorCancel.setText("Cancel");
        btnNewDonorCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDonorCancelCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dlgNewDonorLayout = new org.jdesktop.layout.GroupLayout(dlgNewDonor.getContentPane());
        dlgNewDonor.getContentPane().setLayout(dlgNewDonorLayout);
        dlgNewDonorLayout.setHorizontalGroup(
            dlgNewDonorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgNewDonorLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(dlgNewDonorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dlgNewDonorLayout.createSequentialGroup()
                        .add(btnCreateNewDonor)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnNewDonorCancel))
                    .add(dlgNewDonorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(lblNewDonorPhone)
                        .add(lblNewDonorName)
                        .add(txtNewDonorName)
                        .add(txtNewDonorPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        dlgNewDonorLayout.setVerticalGroup(
            dlgNewDonorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgNewDonorLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(lblNewDonorName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtNewDonorName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lblNewDonorPhone)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtNewDonorPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(dlgNewDonorLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCreateNewDonor)
                    .add(btnNewDonorCancel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dlgNewCharity.setTitle("New Charity");
        dlgNewCharity.setBounds(new java.awt.Rectangle(4, 22, 301, 204));

        lblNewCharityName.setText("Name");

        lblNewCharityTaxId.setText("Tax ID");

        btnCreateNewCharity.setText("Ok");
        btnCreateNewCharity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewCharityCmd(evt);
            }
        });

        btnNewDonorCancel1.setText("Cancel");
        btnNewDonorCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCharityCancelCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dlgNewCharityLayout = new org.jdesktop.layout.GroupLayout(dlgNewCharity.getContentPane());
        dlgNewCharity.getContentPane().setLayout(dlgNewCharityLayout);
        dlgNewCharityLayout.setHorizontalGroup(
            dlgNewCharityLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgNewCharityLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(dlgNewCharityLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dlgNewCharityLayout.createSequentialGroup()
                        .add(btnCreateNewCharity)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnNewDonorCancel1))
                    .add(dlgNewCharityLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(lblNewCharityTaxId)
                        .add(lblNewCharityName)
                        .add(txtNewCharityName)
                        .add(txtNewCharityTaxId, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        dlgNewCharityLayout.setVerticalGroup(
            dlgNewCharityLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgNewCharityLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(lblNewCharityName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtNewCharityName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lblNewCharityTaxId)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtNewCharityTaxId, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(dlgNewCharityLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCreateNewCharity)
                    .add(btnNewDonorCancel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dlgDonationsTable.setTitle("Donations");
        dlgDonationsTable.setBounds(new java.awt.Rectangle(4, 22, 512, 395));

        tblDonationsTable.setModel(tableModel);
        jScrollPane3.setViewportView(tblDonationsTable);

        btnCloseDonationTable.setText("Close");
        btnCloseDonationTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDonationsTableCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout dlgDonationsTableLayout = new org.jdesktop.layout.GroupLayout(dlgDonationsTable.getContentPane());
        dlgDonationsTable.getContentPane().setLayout(dlgDonationsTableLayout);
        dlgDonationsTableLayout.setHorizontalGroup(
            dlgDonationsTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, dlgDonationsTableLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 454, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33))
            .add(dlgDonationsTableLayout.createSequentialGroup()
                .add(192, 192, 192)
                .add(btnCloseDonationTable)
                .addContainerGap())
        );
        dlgDonationsTableLayout.setVerticalGroup(
            dlgDonationsTableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dlgDonationsTableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCloseDonationTable)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDonorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Donor"));

        listDonorBox.setModel(donorModel);
        listDonorBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listDonorBox);

        btnNewDonor.setText("New Donor");
        btnNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDonorCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlDonorPanelLayout = new org.jdesktop.layout.GroupLayout(pnlDonorPanel);
        pnlDonorPanel.setLayout(pnlDonorPanelLayout);
        pnlDonorPanelLayout.setHorizontalGroup(
            pnlDonorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDonorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlDonorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnNewDonor)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDonorPanelLayout.setVerticalGroup(
            pnlDonorPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDonorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnNewDonor))
        );

        pnlCharityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Charity"));

        listCharityBox.setModel(charityModel);
        listCharityBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listCharityBox);

        btnNewCharity.setText("New Charity");
        btnNewCharity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCharityCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlCharityPanelLayout = new org.jdesktop.layout.GroupLayout(pnlCharityPanel);
        pnlCharityPanel.setLayout(pnlCharityPanelLayout);
        pnlCharityPanelLayout.setHorizontalGroup(
            pnlCharityPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlCharityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlCharityPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(pnlCharityPanelLayout.createSequentialGroup()
                        .add(btnNewCharity)
                        .add(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCharityPanelLayout.setVerticalGroup(
            pnlCharityPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlCharityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
                .add(btnNewCharity))
        );

        pnlDonationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Donation"));

        btnMakeDonation.setText("Donate");
        btnMakeDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeDonationCmd(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlDonationPanelLayout = new org.jdesktop.layout.GroupLayout(pnlDonationPanel);
        pnlDonationPanel.setLayout(pnlDonationPanelLayout);
        pnlDonationPanelLayout.setHorizontalGroup(
            pnlDonationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDonationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(txtDonationAmountBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnMakeDonation)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDonationPanelLayout.setVerticalGroup(
            pnlDonationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlDonationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlDonationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtDonationAmountBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnMakeDonation))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        mitemOpen.setText("Open");
        mitemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemOpenCmd(evt);
            }
        });
        menuFile.add(mitemOpen);

        mitemSave.setText("Save");
        mitemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSaveCmd(evt);
            }
        });
        menuFile.add(mitemSave);

        mitemExit.setText("Exit");
        mitemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemExitCmd(evt);
            }
        });
        menuFile.add(mitemExit);

        MenuBar.add(menuFile);

        menuTools.setText("Tools");

        mitemDisplayDonations.setText("Display Donations");
        mitemDisplayDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDisplayDonationsCmd(evt);
            }
        });
        menuTools.add(mitemDisplayDonations);

        MenuBar.add(menuTools);

        setJMenuBar(MenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pnlDonorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(pnlCharityPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(pnlDonationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(pnlCharityPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlDonorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlDonationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemOpenCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemOpenCmd

        ClearModels();

        String sLineIn;
        String sWaiting;
        String[] saFieldsOuter;
        String[] saFieldsInner;

        ArrayList<Donor> donors = new ArrayList<Donor>();
        String donorname;
        String donorphone;
        ArrayList<Donation> donations = new ArrayList<Donation>();
        double donationamount;
        String donationdate;
        ArrayList<Charity> charities = new ArrayList<Charity>();
        String charityname;
        String charitytaxid;

        try {
            File dataFile = new File("donordata.dat");
            Scanner donorReader = new Scanner(dataFile);
            while (donorReader.hasNext()) {
                sLineIn = donorReader.nextLine();
                saFieldsOuter = sLineIn.split(cPattern);
                sWaiting = saFieldsOuter[2];
                donorname = saFieldsOuter[0];
                donorphone = saFieldsOuter[1];
                Donor newDonor = new Donor(donorname, donorphone);
                saFieldsOuter = sWaiting.split(pPattern);
                int i = 0;
                for (String rawhistory : saFieldsOuter) {

                    saFieldsInner = rawhistory.split(ampPattern);
                    sWaiting = saFieldsInner[0];
                    charityname = saFieldsInner[1];
                    charitytaxid = saFieldsInner[2];
                    charities.add(new Charity(charityname, charitytaxid));
                    saFieldsInner = sWaiting.split(modPattern);
                    donationamount = Double.parseDouble(saFieldsInner[0]);
                    donationdate = saFieldsInner[1];
                    donations.add(new Donation(donationamount, donationdate, charities.get(i)));
                    i++;
                }

                for (Donation DD : donations) {
                    newDonor.MakeDonation(DD);
                }
                donors.add(newDonor);
                donations.clear();
                charities.clear();
            }
            donorReader.close();
            for (Donor D : donors) {
                donorList.add(D);
                donorModel.addElement(D.getName());
            }
            File charitiesFile = new File("charities.dat");
            Scanner charitiesReader = new Scanner(charitiesFile);
            charities.clear();
            while (charitiesReader.hasNext()) {
                sLineIn = charitiesReader.nextLine();
                saFieldsOuter = sLineIn.split(cPattern);
                charities.add(new Charity(saFieldsOuter[0], saFieldsOuter[1]));
            }
            charitiesReader.close();
            for (Charity C : charities) {
                charityList.add(C);
                charityModel.addElement(C.getName());
            }

            RebuildTable();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Could not open the file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mitemOpenCmd

    private void mitemSaveCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSaveCmd

        String sOut = new String();
        try {
            PrintWriter donorFile = new PrintWriter("donordata.dat");
            for (Donor d : donorList) {
                sOut += d.getName() + cPattern + d.getPhone() + cPattern;
                for (Donation dd : d.getHistory()) {
                    sOut += Double.toString(dd.getAmount()) + modPattern + dd.getDate().toString();
                    sOut += ampPattern + dd.getCharity().getName() + ampPattern + dd.getCharity().getTaxId();
                    sOut += pPattern;
                }
                sOut += "\n";
            }
            donorFile.println(sOut);
            donorFile.close();
            PrintWriter charitiesFile = new PrintWriter("charities.dat");
            for (Charity C : charityList) {
                charitiesFile.println(C.getName() + cPattern + C.getTaxId());
            }
            charitiesFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Could not save the file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mitemSaveCmd

    private void mitemExitCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemExitCmd
        System.exit(0);
    }//GEN-LAST:event_mitemExitCmd

    private void mitemDisplayDonationsCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemDisplayDonationsCmd

        dlgDonationsTable.setVisible(true);
    }//GEN-LAST:event_mitemDisplayDonationsCmd

    private void btnNewDonorCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDonorCmd
        dlgNewDonor.setVisible(true);
    }//GEN-LAST:event_btnNewDonorCmd

    private void btnNewCharityCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCharityCmd
        dlgNewCharity.setVisible(true);
    }//GEN-LAST:event_btnNewCharityCmd

    private void btnMakeDonationCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeDonationCmd

        int donorIndex = listDonorBox.getSelectedIndex();
        int charityIndex = listCharityBox.getSelectedIndex();
        Date today;
        String sToday = new String();
        try {
            Calendar calendar = Calendar.getInstance();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String sDate = dateFormat.format(calendar.getTime());
            today = dateFormat.parse(sDate);
            sToday = today.toString();
        } catch (Exception e) {
        }
        Donation pledge = new Donation(Double.parseDouble(txtDonationAmountBox.getText()), sToday, charityList.get(charityIndex));
        donorList.get(donorIndex).MakeDonation(pledge);

        String dollarAmount = "$" + txtDonationAmountBox.getText();
        tableModel.addRow(new Object[]{donorList.get(donorIndex).getName(), dollarAmount, charityList.get(charityIndex).getName(), sToday});
        txtDonationAmountBox.setText("");
    }//GEN-LAST:event_btnMakeDonationCmd

    private void btnCreateNewDonorCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewDonorCmd

        if (txtNewDonorName.getText().equals("") || txtNewDonorPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Name or phone number is empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Donor donor = new Donor(txtNewDonorName.getText(), txtNewDonorPhone.getText());
            donorList.add(donor);
            donorModel.addElement(donor.getName());
            ClearDialogs();
            dlgNewDonor.setVisible(false);
            db.AddDonor(donor);
        }
    }//GEN-LAST:event_btnCreateNewDonorCmd

    private void btnNewDonorCancelCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDonorCancelCmd
        txtNewDonorName.setText("");
        txtNewDonorPhone.setText("");
        dlgNewDonor.setVisible(false);

    }//GEN-LAST:event_btnNewDonorCancelCmd

    private void btnCreateNewCharityCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewCharityCmd

        if (txtNewCharityName.getText().equals("") || txtNewCharityTaxId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Name or Tax ID is empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Charity charity = new Charity(txtNewCharityName.getText(), txtNewCharityTaxId.getText());
            charityList.add(charity);
            charityModel.addElement(charity.getName());
            ClearDialogs();
            dlgNewCharity.setVisible(false);
            db.AddCharity(charity);
        }
    }//GEN-LAST:event_btnCreateNewCharityCmd

    private void btnNewCharityCancelCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCharityCancelCmd
        txtNewCharityName.setText("");
        txtNewCharityTaxId.setText("");
        dlgNewCharity.setVisible(false);
    }//GEN-LAST:event_btnNewCharityCancelCmd

    private void btnCloseDonationsTableCmd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDonationsTableCmd
        dlgDonationsTable.setVisible(false);
    }//GEN-LAST:event_btnCloseDonationsTableCmd

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharityTrackerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharityTrackerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharityTrackerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharityTrackerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharityTrackerForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnCloseDonationTable;
    private javax.swing.JButton btnCreateNewCharity;
    private javax.swing.JButton btnCreateNewDonor;
    private javax.swing.JButton btnMakeDonation;
    private javax.swing.JButton btnNewCharity;
    private javax.swing.JButton btnNewDonor;
    private javax.swing.JButton btnNewDonorCancel;
    private javax.swing.JButton btnNewDonorCancel1;
    private javax.swing.JDialog dlgDonationsTable;
    private javax.swing.JDialog dlgNewCharity;
    private javax.swing.JDialog dlgNewDonor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNewCharityName;
    private javax.swing.JLabel lblNewCharityTaxId;
    private javax.swing.JLabel lblNewDonorName;
    private javax.swing.JLabel lblNewDonorPhone;
    private javax.swing.JList listCharityBox;
    private javax.swing.JList listDonorBox;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenuItem mitemDisplayDonations;
    private javax.swing.JMenuItem mitemExit;
    private javax.swing.JMenuItem mitemOpen;
    private javax.swing.JMenuItem mitemSave;
    private javax.swing.JPanel pnlCharityPanel;
    private javax.swing.JPanel pnlDonationPanel;
    private javax.swing.JPanel pnlDonorPanel;
    private javax.swing.JTable tblDonationsTable;
    private javax.swing.JTextField txtDonationAmountBox;
    private javax.swing.JTextField txtNewCharityName;
    private javax.swing.JTextField txtNewCharityTaxId;
    private javax.swing.JTextField txtNewDonorName;
    private javax.swing.JTextField txtNewDonorPhone;
    // End of variables declaration//GEN-END:variables
}
